common_back_withholding_tax_simple_rule:
  path: /
  controller: GeoPagosWithholdingTaxBundle:WithholdingTaxSimpleRule:index

common_back_withholding_tax_simple_rule_new:
  path: /new
  controller: GeoPagosWithholdingTaxBundle:WithholdingTaxSimpleRule:new

common_back_withholding_tax_simple_rule_edit:
  path: /{withholdingTaxSimpleRuleId}
  controller: GeoPagosWithholdingTaxBundle:WithholdingTaxSimpleRule:edit

common_back_withholding_tax_simple_rule_delete:
  path: /{withholdingTaxSimpleRuleId}/delete
  controller: GeoPagosWithholdingTaxBundle:WithholdingTaxSimpleRule:delete