<?php

namespace GeoPagos\WithholdingTaxBundle\Command;

use Carbon\Carbon;
use GeoPagos\WithholdingTaxBundle\Services\WithholdingTax\ProvinceCertificateGenerator;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SendWithholdingTaxesReportTaxAgenciesCommand extends Command
{
    public const NAME = 'geopagos:withholding-taxes:tax-agencies-reports';
    private const DESCRIPTION = 'Generates Withholding Tax reports to be reported to tax agencies';
    private const TRUE = 'true';

    /** @var ProvinceCertificateGenerator */
    private $provinceCertificateGenerator;

    public function __construct(ProvinceCertificateGenerator $generateCertificatesByProvince)
    {
        $this->provinceCertificateGenerator = $generateCertificatesByProvince;

        parent::__construct(self::NAME);
    }

    protected function configure(): void
    {
        $this
            ->setDescription(self::DESCRIPTION)
            ->addOption(
                'date',
                null,
                InputArgument::OPTIONAL,
                'Execution date. Format: YYYY-MM-DD.'
            )
            ->addOption(
                'command-id',
                null,
                InputArgument::OPTIONAL,
                'Execution id meant to track logs generated by this command.'
            )
            ->addOption(
                'recreate-withholding-tax',
                'recreate',
                InputArgument::OPTIONAL,
                'States if withholding_tax data should be recreated from details (default=true)',
                self::TRUE
            );
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        if ($date = $input->getOption('date')) {
            $this->provinceCertificateGenerator->setDate(Carbon::parse($date));
        }

        $recreateWithholdingTax = self::TRUE === $input->getOption('recreate-withholding-tax');
        $this->provinceCertificateGenerator->process($recreateWithholdingTax);
    }
}
